name: Compile TypeScript Mods

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Compile main.mod.ts files in place
        shell: bash
        run: |
          for file in PolyPack/*/main.mod.ts; do
            dir=$(dirname "$file")
            echo "Compiling $file..."
            tsc "$file" --project tsconfig.json --outDir "$dir"
          done
