# .github/workflows/compile-typescript.yml
name: Compile TypeScript on dev

on:
  push:
    branches:
      - dev

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install TypeScript
        run: npm install typescript --no-save

      - name: Compile main.mod.ts → main.mod.js
        run: |
          npx tsc \
            --target ES2017 \
            --module commonjs \
            --rootDir . \
            --outDir . \
            PolyPack/0.1.0/main.mod.ts