name: Compile Ts

on:
  push:
    branches:
      - dev

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install TypeScript
        run: npm install typescript --no-save
        working-directory: reposrc

      - name: Ensure tsconfig.json/jsconfig.json exist
        run: |
          if [ ! -f reposrc/tsconfig.json ]; then
            cat > reposrc/tsconfig.json << 'EOF'
{
  "compilerOptions": {
    "rootDir": ".",
    "outDir": ".",
    "target": "ES2017",
    "module": "commonjs",
    "strict": true
  },
  "include": ["PolyPack/0.1.0/main.mod.ts"]
}
EOF
          fi
          if [ ! -f reposrc/jsconfig.json ]; then
            cat > reposrc/jsconfig.json << 'EOF'
{
  "compilerOptions": {
    "checkJs": true
  },
  "include": ["**/*.js"]
}
EOF
          fi

      - name: Compile main.mod.ts
        run: |
          npx tsc \
            --project reposrc/tsconfig.json \
            --rootDir reposrc \
            --outDir reposrc \
            reposrc/PolyPack/0.1.0/main.mod.ts
