# .github/workflows/compile-typescript.yml
name: Compile Ts

on:
  push:
    branches:
      - dev

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      # 1) checkout your code
      - name: Checkout
        uses: actions/checkout@v3

      # 2) set up Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) install TypeScript locally and compile the single file
      - name: Compile main.mod.ts → main.mod.js
        run: |
          cd reposrc
          npm install typescript --no-save
          npx tsc \
            --target ES2017 \
            --module commonjs \
            --outFile PolyPack/0.1.0/main.mod.js \
            PolyPack/0.1.0/main.mod.ts
