name: Promote PolyPack to main

on:
  workflow_dispatch:

permissions:
  contents: write  # allows pushing and creating releases

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Checkout main branch into ./main
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Copy and clean files
        run: |
          # Remove old versions from main
          rm -rf main/PolyPack
          rm -rf main/PolyPacks
          rm -rf main/ImagePack

          # Recreate necessary folders
          mkdir -p main/PolyPack
          mkdir -p main/PolyPacks
          mkdir -p main/ImagePack

          # Copy contents from dev into main branch folders
          cp -r PolyPack/* main/PolyPack/
          cp -r PolyPacks/* main/PolyPacks/
          cp -r ImagePack/* main/ImagePack/

          # Remove PolyPack/tempcode if it exists
          rm -rf main/PolyPack/tempcode

          # Delete all .ts files recursively in main
          find main -type f -name "*.ts" -delete

          # Replace /PolyPacks/dev/ → /PolyPacks/main/ in all .js files
          find main -type f -name "*.js" -exec sed -i 's|/PolyPacks/dev/|/PolyPacks/main/|g' {} +


      - name: Commit and push if changes exist
        id: commit
        run: |
          cd main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add PolyPack PolyPacks ImagePack modpackTools.js
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: promote modpack files from dev"
            git push origin main
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
